name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Start application
      run: |
        npm start &
        sleep 10  # Give the application some time to start
        # Optionally, you could run additional commands to check if the app started successfully
        curl http://localhost:3000  # Replace with your app’s URL and port
        # If the app needs to be stopped after testing:
        pkill -f "node server.js"  # Replace with the command to stop your app if necessary

    
